name: NexaShop CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install pytest pytest-cov

    - name: Automated Build
      run: echo "Building NexaShop application..."

    - name: Unit Tests with coverage
      run: pytest test_app.py -v --cov=app --cov-report=xml --cov-report=term-missing -k "test_get"

    - name: Integration Tests
      run: pytest test_app.py -v --cov=app --cov-report=xml --cov-report=term-missing -k "test_calculate"

    - name: Static Code Analysis - SonarCloud
      uses: SonarSource/sonarqube-scan-action@fd88b7d7ccbaefd23d8f36f73b59db7a3d246602 # v6.0.0
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: https://sonarcloud.io
      with:
        args: >
          -Dsonar.organization=deejascode
          -Dsonar.projectKey=deejasCode_nexashop-cicd
          -Dsonar.python.version=3.10
          -Dsonar.sources=.
          -Dsonar.exclusions=test_app.py
          -Dsonar.tests=test_app.py
          -Dsonar.python.coverage.reportPaths=coverage.xml

    - name: Build Docker image
      run: echo "Building NexaShop Docker image and pushing to Docker Hub..."

    - name: Deploy to staging
      run: echo "Deploying container to minikube staging environment..."

    - name: Manual approval checkpoint
      run: echo "Awaiting Operations Team approval for production deployment..."

    - name: Deploy to production
      run: echo "Deploying to AWS EKS production environment..."

    - name: Notify deployment success
      run: echo "NexaShop pipeline completed successfully!"
